services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lumma
      POSTGRES_PASSWORD: lumma123
      POSTGRES_DB: lumma
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
